# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GMYmsSB87Sf_QIzk0NglHZHurZUhC9Uf
"""

# app.py
import streamlit as st
import yfinance as yf
import pandas as pd

st.title("📊 Fundamental Stock Analyzer")

ticker = st.text_input("Enter Stock Ticker:", "AAPL")

if ticker:
    stock = yf.Ticker(ticker)
    info = stock.get_info()

    data = {
        "Company Name": info.get("longName"),
        "Sector": info.get("sector"),
        "Market Cap": info.get("marketCap"),
        "P/E Ratio": info.get("trailingPE"),
        "EPS": info.get("trailingEps"),
        "Dividend Yield": info.get("dividendYield"),
        "Revenue (TTM)": info.get("totalRevenue"),
        "Net Income (TTM)": info.get("netIncomeToCommon"),
        "Profit Margin": info.get("profitMargins"),
        "Return on Equity (ROE)": info.get("returnOnEquity"),
        "Debt to Equity": info.get("debtToEquity"),
    }
    if market_cap:
        market_cap_billion = round(market_cap / 1e9, 2)
        data["Market Cap (Billion ₹)"] = f"{market_cap_billion} B"
    else:
        data["Market Cap (Billion ₹)"] = "N/A"

    df = pd.DataFrame(data.items(), columns=["Metric", "Value"])
    st.dataframe(df)
