# -*- coding: utf-8 -*-
"""enrich_nse_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bCFEdjWo8Sg1yyjzXDSNk6kyWFqkjPvJ
"""

# enrich_nse_data.py
import pandas as pd
import yfinance as yf
import time
import os

input_csv_path = "nse stocks.csv"
output_csv_path = "nse_stocks_enriched.csv"

if not os.path.exists(input_csv_path):
    print(f"Error: {input_csv_path} not found. Please ensure your 'nse_stocks.csv' is in the same directory.")
    exit()

try:
    df = pd.read_csv(input_csv_path)
except Exception as e:
    print(f"Error reading {input_csv_path}: {e}")
    exit()

# Add new columns if they don't exist
if 'Sector' not in df.columns:
    df['Sector'] = None
if 'Industry' not in df.columns:
    df['Industry'] = None

print(f"Starting to enrich {len(df)} NSE stock entries with Sector and Industry...")
print("This may take a long time due to API calls. Please be patient.")

for index, row in df.iterrows():
    symbol = row['Symbol']
    # Only fetch if Sector or Industry is missing/empty
    if pd.isna(row['Sector']) or row['Sector'] == 'N/A' or \
       pd.isna(row['Industry']) or row['Industry'] == 'N/A':

        full_ticker = f"{symbol}.NS"
        try:
            stock_yf = yf.Ticker(full_ticker)
            info = stock_yf.info

            sector_val = info.get('sector', 'N/A')
            industry_val = info.get('industry', 'N/A')

            df.loc[index, 'Sector'] = sector_val
            df.loc[index, 'Industry'] = industry_val

            if index % 50 == 0: # Print progress every 50 stocks
                print(f"Progress: {index}/{len(df)} - Fetched {symbol} (Sector: {sector_val}, Industry: {industry_val})")
            time.sleep(0.1) # Be polite to the YFinance API - adjust if hitting limits

        except Exception as e:
            # Mark as error if data couldn't be fetched
            df.loc[index, 'Sector'] = 'Error'
            df.loc[index, 'Industry'] = 'Error'
            print(f"Could not fetch info for {symbol} ({index}/{len(df)}): {e}")
            time.sleep(0.5) # Wait longer on error to avoid blocks

# Save the enriched DataFrame to a new CSV
df.to_csv(output_csv_path, index=False)
print(f"\nEnrichment complete. Data saved to {output_csv_path}")
print(f"Please rename '{output_csv_path}' to 'nse_stocks.csv' (or copy it) to use with your Streamlit app.")