# -*- coding: utf-8 -*-
"""ROCE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bCFEdjWo8Sg1yyjzXDSNk6kyWFqkjPvJ
"""

pip install requests

import requests

def get_roce_from_screener(ticker_name):
    try:
        url = f"https://www.screener.in/company/{ticker_name}/consolidated/"
        headers = {"User-Agent": "Mozilla/5.0"}
        response = requests.get(url, headers=headers)

        if response.status_code == 200:
            text = response.text
            # Search for "ROCE" in the page and extract %
            index = text.find("ROCE")
            snippet = text[index:index+100]
            import re
            match = re.search(r"(\d+\.\d+)%", snippet)
            if match:
                roce_value = float(match.group(1))
                return f"{roce_value}%"
        return "N/A"
    except:
        return "N/A"

